"""Pydantic models for the scriptwriter LLM output — schema v3.0 (I2V single scene).

Module 008 / Delta 008.

The I2V path (Layer A) replaces the multi-clip structure with a single
``Scene`` that describes the body shot: one 10-second clip generated by
Kling from the winner character's photo.

Key differences from v2 (ScriptwriterResponse):
- ``clips`` list replaced by a single ``scene: Scene``.
- ``visual_prompt`` describes the 10-second body action, NOT a static frame.
  The ASCII-ratio validator is kept (80 % rule, same as v2).
- ``cliffhanger`` (1-2 sentences, ~120 chars) is shown as the intro overlay
  text. Kept short so it fits the 2-second drawtext.
- ``next_cliffhanger_seed`` seeds the NEXT episode's LLM prompt.

The intro (2s) and outro (2s) clips are assembled by the pipeline from
``assets/intro_bg.png`` + ``assets/outro.mp4``; they are NOT in the script.
"""

from __future__ import annotations

from pydantic import BaseModel, Field, field_validator

# ---------------------------------------------------------------------------
# Scene (single body clip, 10 s)
# ---------------------------------------------------------------------------


class Scene(BaseModel):
    """The 10-second body shot generated by I2V from the winner's photo."""

    visual_prompt: str = Field(
        ...,
        description=(
            "English-only action description for the I2V model. "
            "Must be > 80 % ASCII printable characters."
        ),
    )
    narration: str = Field(
        ...,
        description="Spanish narration for the TTS voice-over (≤ 300 chars).",
        max_length=300,
    )
    mood: str = Field(
        ...,
        description="One-word mood tag (e.g. 'tense', 'hopeful', 'chaotic').",
        max_length=30,
    )

    @field_validator("visual_prompt")
    @classmethod
    def _ascii_ratio(cls, v: str) -> str:
        if not v:
            raise ValueError("visual_prompt must not be empty")
        printable_ascii = sum(1 for c in v if 0x20 <= ord(c) <= 0x7E)
        ratio = printable_ascii / len(v)
        if ratio < 0.80:
            raise ValueError(
                f"visual_prompt must be > 80 % ASCII printable "
                f"(got {ratio:.0%}): {v!r}"
            )
        return v


# ---------------------------------------------------------------------------
# Top-level response
# ---------------------------------------------------------------------------


class ScriptwriterResponseV3(BaseModel):
    """Full scriptwriter response for the I2V path (v3.0)."""

    title: str = Field(..., description="Episode title (Spanish, ≤ 80 chars).", max_length=80)
    synopsis: str = Field(
        ...,
        description="2-3 sentence episode synopsis for the DB (Spanish).",
        max_length=500,
    )
    cliffhanger: str = Field(
        ...,
        description=(
            "1-2 sentence cliffhanger shown as the intro overlay text "
            "(Spanish, ≤ 120 chars). Short enough to fit a 2-second drawtext."
        ),
        max_length=120,
    )
    scene: Scene
    next_cliffhanger_seed: str = Field(
        ...,
        description="Short seed phrase to feed the next episode's LLM prompt.",
        max_length=200,
    )
